MMR.TOPControls.Web/ViewModels/LoginViewModel.cs
namespace MMR.TOPControls.Web.ViewModels
{
    public class LoginViewModel
    {
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string Message { get; set; }
    }
}

MMR.TOPControls.Web/Controllers/AuthenticationController.cs
using System.Web.Mvc;
using System.Linq;
using AutoMapper;
using Lib.TOPControls;
using Lib.TOPControls.DataAccess;
using Lib.TOPControls.Provider;
using MMR.TOPControls.Web.Areas.Admin.ViewModels;
using MMR.TOPControls.Web.Security;
using MMR.TOPControls.Web.ViewModels;
using Lib.TOPControls.Exceptions;
using System;

namespace MMR.TOPControls.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly LocalDataMembershipProvider service;
        private readonly TOPControlLibrary dataService;
        private readonly IFormsAuthenticationService authenticationService;

        public AuthenticationController(IFormsAuthenticationService authenticationService)
        {
            service = new LocalDataMembershipProvider();
            dataService = new TOPControlLibrary(new TOPControlSQLDAL());
            this.authenticationService = authenticationService;
        }

        public ActionResult Login()
        {
            if (IsNotStarted())
            {
                return RedirectToAction("Startup");
            }
            return View(new LoginViewModel());
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel viewModel)
        {
            var validated = service.ValidateUser(viewModel.EmailAddress, viewModel.Password);

            if (validated)
            {
                var user = dataService.UserActions.FindByUsername(viewModel.EmailAddress);
                if (user != null && user.UserJobs.Count > 0)
                {
                    var jobID = (user.DefaultJobID.HasValue ? user.DefaultJobID.Value : user.UserJobs.First().JobID);
                    var currentJob = dataService.JobActions.Find(jobID);
                    var currentJobViewModel = Mapper.Map<JobInfoViewModel>(currentJob);

                    if (HttpContext.Session != null) HttpContext.Session["CurrentJob"] = currentJobViewModel;

                    authenticationService.Login(viewModel.EmailAddress);
                    return Redirect(authenticationService.GetRedirectUrl());
                }
                
                if (user != null)
                {
                    ModelState.AddModelError("EmailAddress", "User does not have access to a job.  A manager or administrator will need to add job access.");
                }
                else
                {
                    ModelState.AddModelError("EmailAddress", "User credentials validated, but user cannot be found.");
                }
            }

            viewModel.Message = "Error validating user credentials";
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Logout()
        {
            authenticationService.Logout();
            return RedirectToAction("Login");
        }


        public ActionResult Startup()
        {
            if (!IsNotStarted())
            {
                return RedirectToAction("Login");
            }

            return View(new SystemSetupViewModel());
        }


        [HttpPost]
        public ActionResult Startup(SystemSetupViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.AdminPassword == viewModel.ConfirmPassword)
                {
                    try
                    {
                        var sHelper = new Lib.TOPControls.Helpers.StartupHelper(dataService);
                        sHelper.StartupJob(viewModel.InitialJobTitle, viewModel.AdminPassword);
                        return RedirectToAction("Login");
                    }
                    catch (ValidationFailureException vfex)
                    {
                        var vr = vfex.FailedValidationResult;
                        foreach (var rv in vr.RuleViolations)
                        {
                            if (rv.PropertyName == "InitialJobTitle"
                                || rv.PropertyName == "AdminPassword")
                            {
                                ModelState.AddModelError(rv.PropertyName, rv.ErrorMessage);
                            }
                            else
                            {
                                ModelState.AddModelError("", rv.ErrorMessage);
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        ModelState.AddModelError("", ex.Message);
                    }
                }
                else
                {
                    ModelState.AddModelError("AdminPassword", "The two password values entered do not match.  Please try again.");
                }
            }
            return View(viewModel);
        }

        private bool IsNotStarted()
        {
            var allusers = dataService.UserActions.Search("");
            var alljobs = dataService.JobActions.Search("");

            return !allusers.Any() && !alljobs.Any();
        }

    }
}

MMR.TOPControls.Web/Views/Authentication/Login.cshtml
@model MMR.TOPControls.Web.ViewModels.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

@using (Html.BeginForm("Login", "Authentication", new { ReturnUrl = Request.Params["ReturnUrl"] }, FormMethod.Post, new { @class = "form-signin" }))
{
    <center>
        <img src="@Url.Content("~/Assets/img/Logo_Main_Registered.jpg")" alt="MMR Group">
    </center>
    
    <h2 class="form-signin-heading">Login</h2>
    <div class="input-prepend">
        <span class="add-on"><i class="icon-user"></i></span>
        @Html.TextBoxFor(x => x.EmailAddress, new { @class = "", placeholder = "Email Address", autofocus = "autofocus" })    
    </div>
    <div class="input-prepend">
        <span class="add-on"><i class="icon-lock"></i></span>
        @Html.PasswordFor(x => x.Password, new { @class = "", placeholder = "Password" })    
    </div>
    
    <p></p>
    
    <button class="btn btn-primary" type="submit">Login</button>

    <div class="field-validation-error" id="error">
        @Model.Message
    </div>
    
    <div id="modal-container" class="modal hide">
    </div>
}

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            TopControls.user.init();
        });
    </script>
}

MMR.TOPControls.Web/Views/Authentication/Startup.cshtml
@model MMR.TOPControls.Web.ViewModels.SystemSetupViewModel

@{
    ViewBag.Title = "Application Startup";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}


<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Startup", "Authentication", FormMethod.Post, new { @class = "form-startup" }))
{
    
    <center>
        <img src="@Url.Content("~/Assets/img/Logo_Group_500x259.png")" alt="MMR Group">
    </center>
    <legend>
        Setup the TOPControls Application
    </legend>
       
    <fieldset>
        <h4>The database appears to be empty. Before the TOPControls system can be used, this system will need a 
            sysadmin account and at least one job.  Enter the Job Name below, followed by the system administrator 
            password.
        </h4>
        @Html.ValidationSummary(true, "There were some problems encountered while attempting create the job or user account:", new { @class = "input-validation-error" })
        <div class="control-group">
            @Html.LabelFor(model => model.InitialJobTitle)
			<div class="controls">
				@Html.TextBoxFor(model => model.InitialJobTitle, new { @class = "", placeholder = "Job Number and Name", autofocus = "autofocus", autocomplete="off" })
				@Html.ValidationMessageFor(model => model.InitialJobTitle, null, new { style="display:block;" } )
			</div>
		</div>

        <div class="control-group">
            @Html.LabelFor(model => model.AdminPassword)
			<div class="controls">
				@Html.PasswordFor(model => model.AdminPassword, new { @class = "", placeholder = "Administrator Password" })
				@Html.ValidationMessageFor(model => model.AdminPassword, null, new { style="display:block;" })
			</div>
		</div>

        <div class="control-group">
            @Html.LabelFor(model => model.ConfirmPassword)
            <div class="controls">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "", placeholder = "Confirm Password" })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, null, new { style="display:block;" })
            </div>
        </div>

		<div class="form-actions">
			<input type="submit" class="btn btn-primary" value="Get Started!" />
		</div>
    </fieldset>

    
}