MMR.TOPControls.Web/Areas/Admin/ViewModels/JobSettingsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;
using Lib.TOPControls;

namespace MMR.TOPControls.Web.Areas.Admin.ViewModels
{
    public class JobSettingsViewModel
    {
        public long Id { get; set; }

        public IEnumerable<UserJob> JobUsers { get; set; }

        public IEnumerable<TOPUser> AvailableJobUsers { get; set; }

        public bool ShowEarnedToClient { get; set; }

        [DisplayName("Calculate Completions")]
        public bool WeightedCalculations { get; set; }

        public SelectList WeightedCalculationsOptions
        {
            get
            {
                var options = new List<SelectListItem>
                {
                    new SelectListItem {Text = "Weighted Average of Man-Hours", Value = "true"},
                    new SelectListItem {Text = "Simple One-to-One Values", Value = "false"}
                };

                return new SelectList(options, "Value", "Text");
            }
        }

        public bool HistoricalScopeCurve { get; set; }

        public SelectList HistoricalScopeCurveOptions
        {
            get
            {
                var options = new List<SelectListItem>
                {
                    new SelectListItem {Text = "Use Current Scope and Man-Hours", Value = "false"},
                    new SelectListItem {Text = "Use Scope and Weight Values at Time of Entry", Value = "true"}
                };

                return new SelectList(options, "Value", "Text");
            }
        }
    }
}

MMR.TOPControls.Web/Areas/Admin/Controllers/JobSettingsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Lib.TOPControls;
using Lib.TOPControls.DataAccess;
using MMR.TOPControls.Web.Areas.Admin.ViewModels;

namespace MMR.TOPControls.Web.Areas.Admin.Controllers
{
    public class JobSettingsController : AdminBaseController
    {
        private readonly TOPControlLibrary service;

        public JobSettingsController()
        {
            service = new TOPControlLibrary(new TOPControlSQLDAL());
        }

        public ActionResult Index(long? id)
        {
            if (id.HasValue && id.Value > 0)
            {
                if (User.IsInRole("TOPAdmin") || service.UserJobActions.AllForJob(id.Value).Any(uj => uj.UserID == CurrentUser.ID))
                {
                    // try to switch to the indicated job
                    var job = service.JobActions.Find(id.Value);

                    CurrentJob = Mapper.Map<JobInfoViewModel>(job);
                }
                else
                {
                    return RedirectToAction("Index", "JobInfo", new { area = "Admin" });
                }
            }

            var viewModel = new JobSettingsViewModel
            {
                Id = CurrentJob.ID,
                ShowEarnedToClient = CurrentJob.ShowEarnedToClient,
                WeightedCalculations = CurrentJob.WeightedCalculations,
                HistoricalScopeCurve = CurrentJob.HistoricalScopeCurve
            };

            return View(viewModel);
        }



        [HttpPost]
        public ActionResult Index(JobSettingsViewModel viewModel)
        {
            var jobInfo = service.JobActions.Find(viewModel.Id);

            jobInfo.ShowEarnedToClient = viewModel.ShowEarnedToClient;
            jobInfo.WeightedCalculations = viewModel.WeightedCalculations;
            jobInfo.HistoricalScopeCurve = viewModel.HistoricalScopeCurve;

            if (PerformAction(() => service.JobActions.Update(jobInfo, CurrentUser.ID)))
            {
                return RedirectToAction("Index", "ProjectStatus", new { area = "" });
            }
            CurrentJob = Mapper.Map<JobInfoViewModel>(jobInfo);

            return View(viewModel);
        }

        public ActionResult JobSettingsUsers()
        {
            var jobUsers = service.UserJobActions.AllForJob(CurrentJob.ID).ToList();

            var viewModel = new JobSettingsViewModel
            {
                JobUsers = jobUsers,
                AvailableJobUsers =
                    service.UserActions.Search("").Where(u => !jobUsers.Select(uj => uj.UserID).Contains(u.ID))
            };

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddUser(long id)
        {
            var userJob = new UserJob
            {
                JobID = CurrentJob.ID,
                UserID = id
            };

            try
            {
                service.UserJobActions.Add(userJob, CurrentUser.ID);

                return Json(new {success = true});
            }
            catch (Exception e)
            {
                return Json(new {success = false, message = e.Message});
            }
        }

        [HttpPost]
        public ActionResult RemoveUser(long id)
        {
            try
            {
                service.UserJobActions.Delete(id, CurrentUser.ID);

                return Json(new {success = true});
            }
            catch (Exception e)
            {
                return Json(new {success = false, message = e.Message});
            }
        }
    }
}

MMR.TOPControls.Web/Areas/Admin/Views/JobSettings/Index.cshtml
@model MMR.TOPControls.Web.Areas.Admin.ViewModels.JobSettingsViewModel
@using MMR.TOPControls.Web.Helpers;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h2>Job Settings</h2>
</div>

<div id="job-settings-container" class="span6">
@using (Html.BeginForm(null,null, FormMethod.Post))
{
    <div class="modal-body form-horizontal">
        @Html.HiddenFor(x => x.Id)
        <div class="control-group">
            @Html.LabelFor(x => x.ShowEarnedToClient, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.ShowEarnedToClient)
                @Html.ValidationMessageFor(x => x.ShowEarnedToClient)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.WeightedCalculations, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(x=>x.WeightedCalculations, Model.WeightedCalculationsOptions, new { @class = "span3"})
                <p class="alert">
                    Calculating weighted values requires that all items have commodities assigned to them, and that those commodities have non-zero Man-Hours assigned. 
                </p>
                @Html.ValidationMessageFor(x => x.WeightedCalculations)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.HistoricalScopeCurve, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(x => x.HistoricalScopeCurve, Model.HistoricalScopeCurveOptions, new { @class = "span3" })
                <p class="alert">
                    Changing the Historical Progress Calculation value will cause all Historical Progress curves to be recalculated.  This may take a few minutes and may slow operation of the Project Status display and some reports.
                </p>
                @Html.ValidationMessageFor(x => x.HistoricalScopeCurve)
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
    ;
}
</div>

<div class="clearfix"></div>

<div id="userListSection" >
    @Html.Action("JobSettingsUsers")
</div>

@section Scripts
{
    <script>

        var urlMap = {
            userRefreshUrl: '@Url.Action("JobSettingsUsers")'
        };
        
        TopControls.jobSettings.init(urlMap);
    </script>
}

MMR.TOPControls.Web/Areas/Admin/Views/JobSettings/JobSettingsUsers.cshtml
@model MMR.TOPControls.Web.Areas.Admin.ViewModels.JobSettingsViewModel
           
@{
    Layout = null;
}

<div class="row-fluid">
    <div class="span6">
        <h3>Authorized Users</h3>
        <table id="topuser-table" class="table table-striped">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model.JobUsers)
                {
                    <tr>
                        <td>@string.Format("{0} {1} ({2})", user.TOPUser.FirstName, user.TOPUser.LastName, user.TOPUser.Login)</td>
                        <td>
                            <a href="@Url.Action("RemoveUser", "JobSettings", new { id = user.ID})" data-action="remove-user">
                                <i class="icon-trash"></i>remove
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="span6">
        <div class="form-horizontal well">
            <h4>Add Users</h4>
            <hr />
            <table id="topuser-table" class="table table-striped">
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var user in Model.AvailableJobUsers)
                    {
                        <tr>
                            <td>@string.Format("{0} {1} ({2})", user.FirstName, user.LastName, user.Login)</td>
                            <td>
                                <a href="@Url.Action("AddUser", "JobSettings", new { id = user.ID})" data-action="add-user">
                                    <i class="icon-plus-sign"></i>add
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>