MMR.TOPControls.Web/ViewModels/ChangeJobViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace MMR.TOPControls.Web.ViewModels
{
    public class ChangeJobViewModel
    {
        public List<SelectListItem> JobInfoFilter { get; set; }
    }
}

MMR.TOPControls.Web/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lib.TOPControls;
using Lib.TOPControls.DataAccess;
using Lib.TOPControls.DataImport;
using Lib.TOPControls.Interfaces;
using Lib.TOPControls.FileImporter.Version1;
using Lib.TOPControls.Exceptions;
using MMR.TOPControls.Web.ViewModels;
using System.Diagnostics;
using System.Text;

namespace MMR.TOPControls.Web.Controllers
{
    public class ImportController : BaseController
    {

        private readonly TOPControlLibrary service;

        public ImportController()
        {
            service = new TOPControlLibrary(new TOPControlSQLDAL());
        }

        //
        // GET: /Import/

        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Upload()
        {
            var file = Request.Files[0];
            var viewModel = new ImportResultsViewModel
                {
                    ImportSucceeded = false
                };

            if (file != null && file.ContentLength > 0)
            {

                var filename = Path.GetFileName(file.FileName);
                var path = Path.Combine(Path.GetTempPath(), filename);          
                if (System.IO.File.Exists(path)) System.IO.File.Delete(path);

                file.SaveAs(path);
                var fimp = new FileImporterService1(service);

                FileAnalysisResult evalfile = null;
                try
                {
                    evalfile = fimp.ExamineFile(path, "TaskImport");

                }
                catch (FileImportException fex)
                {
                    viewModel = new ImportResultsViewModel
                    {
                        ImportSucceeded = false
                    };
                    ViewBag.UploadFailure  = fex.Message + " \n " + fex.InnerException.ToString();
                    
                }
                if (evalfile != null)
                {
                    if (evalfile.CandidateRecordsets.Count() == 1 && evalfile.CandidateRecordsets.ElementAt(0).SchemaPoints > 2)
                    {
                        var crs = evalfile.CandidateRecordsets.ElementAt(0);
                        var imported = fimp.ReadImportTable(path, "TaskImport", crs.Name, CurrentUser.ID, CurrentJob.ID);
                        var fi = service.FileImportActions.Find(imported.RecordsetID);

                        var timporter = new TaskImporter(service, imported.RecordsetID);
                        try
                        {

                            var newItems = timporter.GetNewItems(new Dictionary<string, string>(), CurrentUser.ID);

                            ViewBag.UploadSuccess = string.Format("Uploaded and processed file {0}, recordset \"{1}\", assigned FileImport ID: {2}. Items successfuly imported: {3}", filename, imported.RecordsetName, imported.RecordsetID, newItems.Count());

                            viewModel = new ImportResultsViewModel
                            {
                                ImportSucceeded = true,
                                PhaseImported = timporter.PhaseImported,
                                TaskImported = timporter.TaskImported,
                                AreasAdded = timporter.AreasAdded,
                                CommoditiesAdded = timporter.CommoditiesAdded,
                                CraftsAdded = timporter.CraftsAdded,
                                ObjectTypesAdded = timporter.ObjectTypesAdded,
                                SystemsAdded = timporter.SystemsAdded,
                                TrackedItemsAdded = timporter.TrackedItemsAdded,
                                TrackedItemsRemoved = timporter.TrackedItemsRemoved
                            };
                        }
                        catch (FileImportException fex)
                        {
                            ViewBag.UploadFailure = String.Format("Problem encountered while importing the data from the file. The import returned the message: " + fex.Message);
                        }
                        catch (ValidationFailureException vfex)
                        {
                            ViewBag.UploadFailure = String.Format("One of the imported items failed validation: {0}", vfex.FailedValidationResult.RuleViolations.ElementAt(0).ErrorMessage);
                        }
                        
                    }
                    else
                    {
                        var bestScore = 0;
                        var bestPosition = -1;
                        foreach (var crs in evalfile.CandidateRecordsets)
                        {
                            if (crs.SchemaPoints > bestScore)
                            {
                                bestScore = crs.SchemaPoints;
                                bestPosition = crs.Position;
                            }
                        }
                        if (bestScore > 2)
                        {
                            var src = evalfile.CandidateRecordsets.FirstOrDefault(rs => rs.Position == bestPosition);
                        
                            var imported = fimp.ReadImportTable(path, "TaskImport", src.Name, CurrentUser.ID, CurrentJob.ID);
                            var fi = service.FileImportActions.Find(imported.RecordsetID);

                            var timporter = new TaskImporter(service, imported.RecordsetID);
                            try
                            {
                                var newItems = timporter.GetNewItems(new Dictionary<string, string>(), CurrentUser.ID);

                                ViewBag.UploadSuccess = string.Format("Uploaded and processed file {0}, recordset \"{1}\", assigned FileImport ID: {2}. Items successfuly imported: {3}", filename, imported.RecordsetName, imported.RecordsetID, newItems.Count());

                                viewModel = new ImportResultsViewModel
                                {
                                    ImportSucceeded = true,
                                    PhaseImported = timporter.PhaseImported,
                                    TaskImported = timporter.TaskImported,
                                    AreasAdded = timporter.AreasAdded,
                                    CommoditiesAdded = timporter.CommoditiesAdded,
                                    CraftsAdded = timporter.CraftsAdded,
                                    ObjectTypesAdded = timporter.ObjectTypesAdded,
                                    SystemsAdded = timporter.SystemsAdded,
                                    TrackedItemsAdded = timporter.TrackedItemsAdded,
                                    TrackedItemsRemoved = timporter.TrackedItemsRemoved
                                };
                            }
                            catch (FileImportException fex)
                            {
                                ViewBag.UploadFailure = String.Format("Problem encountered while importing the data from the file. The import returned the message: " + fex.Message);
                            }
                            catch (ValidationFailureException vfex)
                            {
                                ViewBag.UploadFailure = String.Format("One of the imported items failed validation: {0}", vfex.FailedValidationResult.RuleViolations.ElementAt(0).ErrorMessage);
                            }

                        }
                        else
                        {
                            ViewBag.UploadFailure = "None of the sheets in the uploaded file had enough data to import.";
                        }

                    }

                }
                System.IO.File.Delete(path);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult ExportAll()
        {
            var source = Server.MapPath(@"~\TaskImport.xlsx");
            var target = Server.MapPath(@"~\Files\Temp\Export.xlsx");
            var dt = DateTime.Now;
            target = target.Replace("Export.xlsx", string.Format("{0}_ExportAll_{1}{2}{3}{4}.xlsx",makeFilenameFriendly(CurrentJob.Title), dt.Year, dt.Month, dt.Day, dt.Millisecond));
            while (System.IO.File.Exists(target))
            {
                target = Server.MapPath(@"~\Files\Temp\Export.xlsx").Replace("Export.xlsx", string.Format("{0}_ExportAll_{1}{2}{3}.xlsx", makeFilenameFriendly(CurrentJob.Title), dt.Year, dt.Month, dt.Day, dt.Millisecond));
            }
            var fimp = new FileImporterService1(service);
            
            fimp.ExportJobData(CurrentJob.ID, target, source);

            return new RedirectResult("~/Files/Temp/" + Path.GetFileName(target));

        }

        private string makeFilenameFriendly(string src)
        {
            var result = new StringBuilder();
            var filler="_";
            var badChars = Path.GetInvalidFileNameChars();
            
            foreach(var ch in src.ToCharArray())
            {
                if (badChars.Contains(ch))
                {
                    result.Append(filler);
                }
                else
                {
                    result.Append(ch);
                }
            }
            return result.ToString();

        }
    }
}

MMR.TOPControls.Web/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using MMR.TOPControls.Web.wrefReports;

namespace MMR.TOPControls.Web.Controllers
{
    public class ReportsController : BaseController
    {
        //
        // GET: /Reports/

        public ActionResult Index()
        {
            return View();
        }

        

        public ActionResult Print(string name)
        {
            var svc = new ReportExecutionService();
            string historyID = null;
            var execHeader = new ExecutionHeader();
            svc.Credentials = System.Net.CredentialCache.DefaultCredentials;
            svc.ExecutionHeaderValue = execHeader;

            var execInfo = svc.LoadReport(GetReportPath(name), historyID);
            var parms = execInfo.Parameters;
            var pvals = GetParameterValues(parms);

            var format = "PDF";
            var sessionID = svc.ExecutionHeaderValue.ExecutionID;


            string extension;
            string mimetype;
            string encoding;
            Warning[] warnings;
            string[] streamids;


            byte[] filebytes;
            try
            {
                svc.SetExecutionParameters(pvals.ToArray(), "en-us");
                filebytes = svc.Render(format, null, out extension, out mimetype, out encoding, out warnings, out streamids);

                var result = new FileContentResult(filebytes, mimetype);
                result.FileDownloadName = makeFilenameFriendly(name) + makeFilenameFriendly(CurrentJob.Title) + ".pdf";
                return result;
            }
            catch (Exception ex)
            {
                throw ex; 
            }

            return null;

        }


        protected bool? GetURLValueAsBoolean(string valueName)
        {
            bool? result = null;
            var strVal = Request.QueryString[valueName];
            if (strVal != null)
            {
                bool temp;
                if (bool.TryParse(strVal, out temp))
                {
                    result = temp;
                }
            }
            return result;
        }

        protected string GetReportPath(string name)
        {
            return "/Reports/TOPControls/" + name;
        }

        protected List<ParameterValue> GetParameterValues(ReportParameter[] parms)
        {
            var pvals = new List<ParameterValue>();

            foreach (var x in parms)
            {
                ParameterValue pv = null;
                if (x.Name == "JobID")
                {
                    pv = GetParameterValueInstance(x, CurrentJob.ID);
                }
                else if (x.TypeSpecified && x.Type == ParameterTypeEnum.Boolean)
                {
                    var bvalUrl = GetURLValueAsBoolean(x.Name);
                    if (bvalUrl.HasValue)
                    {
                        pv = GetParameterValueInstance(x, bvalUrl.Value);
                    }
                }
                if (pv != null) pvals.Add(pv);
            }

            return pvals;
        }

        protected ParameterValue GetParameterValueInstance(ReportParameter rp, object value)
        {
            ParameterValue result = null;
            if (rp != null)
            {
                if (value != null || (rp.NullableSpecified && rp.Nullable))
                {
                    result = new ParameterValue { Name = rp.Name, Value = value.ToString() };
                }
                else if (rp.NullableSpecified && rp.Nullable)
                {
                    result = new ParameterValue { Name = rp.Name, Value = null };
                }
            }

            return result;
        }

        private string makeFilenameFriendly(string src)
        {
            var result = new StringBuilder();
            var filler = "_";
            var badChars = System.IO.Path.GetInvalidFileNameChars();

            foreach (var ch in src.ToCharArray())
            {
                if (badChars.Contains(ch))
                {
                    result.Append(filler);
                }
                else
                {
                    result.Append(ch);
                }
            }
            return result.ToString();

        }
    
    }
}

MMR.TOPControls.Web/Views/Shared/_ChangeJob.cshtml
@model MMR.TOPControls.Web.ViewModels.ChangeJobViewModel
@{
    Layout = "";
    
}

@using (Html.BeginForm("ChangeJob", "Home", FormMethod.Post))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><i class="icon-remove" /></button>
        <h3>Change Jobs</h3>
    </div>
    <div class="modal-body form-horizontal">
        <div class="row-fluid">
            <div class="span12">
                <h4>Job: </h4>
                @Html.DropDownList("jobSelector", Model.JobInfoFilter, new
                    {
                        data_select2_default = "", 
                        @class = "input-block-level job-selector ", 
                        data_placeholder = "Please select a job..."
                    })
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Change Job</button>
        <button type="button" class="btn pull-left" data-dismiss="modal">Cancel</button>
    </div>    
}

<script>
    $('#jobSelector').select2({
        width: TopControls.common.select2Width
    });
</script>

MMR.TOPControls.Web/Views/Shared/_Header.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>@ViewBag.Title - MMR TOP Controls</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width" />
<link rel="shortcut icon" href="@Url.Content("~/Assets/img/favicon.ico")">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href='@Url.Content("~/Assets/img/apple-touch-icon-114x114-precomposed.png")'>

MMR.TOPControls.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9 ]>    <html class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <title></title>
    @Html.Partial("_Header")
    @Styles.Render("~/Assets/css/styles")
    <!--[if lt IE 9]><!-->
    @Scripts.Render("~/Assets/js/compatibility")
    <!--<![endif]-->
</head>
<body>
    <div class="top-notification"></div>
    <div id="content">
        <div class="container-fluid content-wrapper">
            <br>
            <div class="logo pull-left">
                <a href="@Url.Action("Index", "Home", new { area = "" })" class="brand">
                    <img src="@Url.Content("~/Assets/img/Logo1.png")" alt="MMR Group Logo">
                </a>
            </div>
            <!-- Bread Crumbs -->
            <ul class="breadcrumb pull-right">
                <li><a href="@Url.Action("Index", "Home", new { area = "" })">T.O.P. Controls</a> <span class="divider">/</span></li>
                @RenderSection("breadcrumb", false)
            </ul>
            <span class="current-job pull-right">
                @Html.Action("CurrentJobDisplay", "Home", new { area = "" })
            </span>
            <div class="clearfix"></div>
            <!-- Nav Bar -->
            <div class="navbar">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a href="@Url.Action("Index", "Home", new { area = "" })" class="brand">T.O.P. Controls</a>
                        <div class="nav-collapse">
                            <ul class="nav pull-right">
                                @if (ViewBag.OverrideDefaultMenu == null)
                                {
                                    <li class="divider-vertical"></li>
                                    @RenderSection("menubar", required: false)
                                    @Html.Partial("_TopNav")
                                }
                                else
                                {
                                    @RenderSection("menubar", required: false)
                                }
                            </ul>
                        </div>
                        <!-- /.nav-collapse -->
                    </div>
                </div>
                <!-- /navbar-inner -->
            </div>
            <!-- Render Body -->
            @RenderBody()
        </div>
        <div id="changeJobModal" class="modal hide fade">
        </div>
        <div id="taskManagementModal" class="modal hide fade"></div>
    </div>
    
    <script>
        var __BaseUrl = '@Url.Action("Index", "Home", new { area=""})';
    </script>

    @Scripts.Render("~/Assets/js/bundle")
    @RenderSection("Scripts", false)

    <script>
        var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
        (function (d, t) {
            var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
            g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g, s);
        }(document, 'script'));
    </script>
</body>
</html>

MMR.TOPControls.Web/Views/Shared/_LoginLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
    <head>
        @Html.Partial("_Header")

        @Styles.Render("~/Assets/css/styles")

        <style type="text/css">
            body
            {
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #f5f5f5;
            }

            .form-signin
            {
                max-width: 300px;
                padding: 19px 29px 29px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }

            .form-startup
            {
                max-width: 500px;
                padding: 19px 29px 29px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }

            input {
                margin-bottom: 10px !important;
            }

            .form-startup input[type=text], .form-startup input[type=password]
            {
                width: 450px;
            }

            #error {
                margin-top: 10px;
            }

            legend
            {
                text-align:center;
            }

            .validation-summary-errors li
            {
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div id="main-content" class="container">
            @RenderBody()
        </div>

        @Scripts.Render("~/Assets/js/bundle")
        @RenderSection("Scripts", false)
    </body>
</html>

MMR.TOPControls.Web/Views/Shared/_TaskPhaseSelector.cshtml
@model MMR.TOPControls.Web.ViewModels.TaskPhaseViewModel
@{
    Layout = "";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><i class="icon-remove" /></button>
    <h3>Task Management</h3>
</div>
<div class="modal-body form-horizontal">
    <div class="row-fluid">
        <div class="span12">
            <h4>Select A Phase To Manage: </h4>
            @Html.DropDownList("taskPhaseSelector", Model.TaskPhaseFilter, new
                    {
                        data_select2_default = "",
                        @class = "input-block-level",
                        data_url = @Url.Action("List", "Task", new { area = "Admin" })
                    })
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" id="btnSubmitPhaseTaskEditSelection">Manage Tasks</button>
    <button type="button" class="btn pull-left" data-dismiss="modal">Cancel</button>
</div>

<script>
    $('#taskPhaseSelector').select2({
        width: TopControls.common.select2Width
    });
</script>

MMR.TOPControls.Web/Views/Shared/_TopNav.cshtml
@if (User.IsInRole("TOPEntry") || User.IsInRole("TOPManager") || User.IsInRole("TOPAdmin"))
{
<li>
    <a href="@Url.Action("Index", "Home", new { area = "" })" data-toggle="modal">
        <i class=" icon-check"></i>Enter Daily Progress
    </a>
</li>
}
<li>
    <a href="@Url.Action("ChangeJob", "Home", new { area = "" })" id="changeJobModalButton">
        <i class=" icon-signin"></i>Change Job
    </a>
</li>
<li>
    <a href="@Url.Action("Index", "ProjectStatus", new { area = "" })">
        <i class="icon-list-alt"></i>Project Status
    </a>
</li>
<li>
    <a href="@Url.Action("Index", "Reports", new { area = "" })">
        <i class="icon-print"></i>Reports
    </a>
</li>

@if (User.IsInRole("TOPAdmin") || User.IsInRole("TOPManager"))
{
    <li class="divider-vertical"></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-cog"></i>Management <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="@Url.Action("Index", "JobSettings", new { area = "Admin" })">
                    <i class="icon-cogs"></i>Job Settings
                </a>
            </li>
            @if (User.IsInRole("TOPAdmin"))
            {
            <li>
                <a href="@Url.Action("List", "JobInfo", new { area = "Admin" })">
                    <i class="icon-briefcase"></i>Jobs
                </a>
            </li>
            }
            <li>
                <a href="@Url.Action("List", "TopUser", new { area = "Admin" })">
                    <i class="icon-group"></i>Users
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("List", "ProjectPhase", new { area = "Admin" })">
                    <i class="icon-sitemap"></i>Phases
                </a>
            </li>
            <li>
                <a href="@Url.Action("ManageTasks", "Home", new { area = "" })" id="manageTasksModalButton">
                    <i class="icon-tasks"></i>Tasks
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "Commodity", new { area = "Admin" })">
                    <i class="icon-barcode"></i>Commodities
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "ObjectType", new { area = "Admin" })">
                    <i class="icon-folder-close"></i>Object Types
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "ProjectSystem", new { area = "Admin" })">
                    <i class="icon-tag"></i>Project Systems
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "ProjectArea", new { area = "Admin" })">
                    <i class=" icon-tags"></i>Project Areas
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "CraftInfo", new { area = "Admin" })">
                    <i class="icon-info-sign"></i>Craft
                </a>
            </li>
            <li>
                <a href="@Url.Action("List", "WorkCrew", new { area = "Admin" })">
                    <i class="icon-group"></i>Work Crews
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="@Url.Action("Index", "Import", new { area = "" })">
                    <i class="icon-upload-alt"></i>Import
                </a>
            </li>
            <li>
                <a href="@Url.Action("ExportAll", "Import", new { area = ""})" target="_blank">
                    <i class="icon-download"></i>Export All
                </a>
            </li>
        </ul>
    </li>
}
<li class="divider-vertical"></li>

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="icon-user"></i>@User.Identity.Name <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="@Url.Action("ChangePassword", "Home", new { area = "" })" data-button-action="edit">
                <i class="icon-lock"></i>Change Password
            </a>
        </li>
        <li>
            <a href="@Url.Action("Logout", "Authentication", new { area = "" })">
                <i class="icon-signout"></i>Log Out
            </a>
        </li>
    </ul>
</li>