MMR.TOPControls.Web/Areas/Admin/ViewModels/TaskViewModel.cs
using System.ComponentModel;
using System.Web.Mvc;
using MMR.TOPControls.Web.Helpers.DataTables.Attributes;
using MMR.TOPControls.Web.ViewModels;

namespace MMR.TOPControls.Web.Areas.Admin.ViewModels
{
    public class TaskViewModel : DomainViewModelBase
    {
        [Searchable]
        [Sortable]
        public string Title { get; set; }

        [DisplayName("Display Order")]
        [Searchable]
        [Sortable]
        public int DisplayOrder { get; set; }

        public long? DefaultCommodityID { get; set; }

        [DisplayName("Default Commodity")]
        public string DefaultCommodity { get; set; }

        [DisplayName("Default Commodity")]
        public SelectList Commodities { get; set; }

        [DisplayName("Replace Default Commodity on Active Items?")]
        public bool PropogateCommodity { get; set; }
    }
}

MMR.TOPControls.Web/Areas/Admin/Controllers/TaskController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Envoc.Core.Shared.Extensions;
using Lib.TOPControls;
using Lib.TOPControls.DataAccess;
using MMR.TOPControls.Web.Areas.Admin.ViewModels;
using MMR.TOPControls.Web.Helpers.DataTables;
using MMR.TOPControls.Web.ViewModels;

namespace MMR.TOPControls.Web.Areas.Admin.Controllers
{
    public class TaskController : AdminBaseController
    {
        private readonly TOPControlLibrary service;

        public TaskController()
        {
            service = new TOPControlLibrary(new TOPControlSQLDAL());
        }

        public ActionResult List(long phaseId)
        {
            var model = new TaskListViewModel
            {
                Phase = service.PhaseActions.Find(phaseId),
                PhaseTasks = GetTaskViewModels(phaseId)
            };
            return View(model);
        }

        public ActionResult ListItems(DataTableRequest request, long phaseId)
        {
            var parser = new DataTableParser<TaskViewModel>(GetTaskViewModels(phaseId));
            var formattedList = parser.Parse(request);
            return Json(formattedList);
        }

        public ActionResult Create(long phaseId)
        {
            var viewModel = new CreateTaskViewModel
            {
                PhaseID = phaseId,
                JobID = CurrentJob.ID
            };

            AddCommodityListToViewModel(viewModel);

            return PartialView(viewModel);
        }

        [HttpPost]
        public ActionResult Create(CreateTaskViewModel viewModel)
        {
            var model = ConvertViewModelToModel(viewModel);
            model.PhaseID = viewModel.PhaseID;

            if (PerformAction(() => service.TaskActions.Add(model, CurrentUser.ID)))
            {
                PropogateCommodity(viewModel.PropogateCommodity, model.ID, model.DefaultCommodityID);

                return Json(new {success = true});
            }

            return PartialView(viewModel);
        }

        public ActionResult Edit(int id)
        {
            var model = service.TaskActions.Find(id);

            if (model.IsNull())
            {
                return new HttpNotFoundResult();
            }

            return PartialView((ConvertModelToViewModel(model)));
        }

        [HttpPost]
        public ActionResult Edit(TaskViewModel viewModel)
        {
            var model = service.TaskActions.Find(viewModel.ID);

            if (model.IsNull())
            {
                return new HttpNotFoundResult();
            }

            Mapper.Map(viewModel, model);

            if (PerformAction(() => service.TaskActions.Update(model, CurrentUser.ID)))
            {
                PropogateCommodity(viewModel.PropogateCommodity, model.ID, model.DefaultCommodityID);
                return Json(new {success = true});
            }

            AddCommodityListToViewModel(viewModel);
            return PartialView(viewModel);
        }

        public ActionResult Delete(int id)
        {
            var model = service.TaskActions.Find(id);

            if (model.IsNull())
            {
                return new HttpNotFoundResult();
            }

            var viewModel = BuildDeletionViewModel(model);

            return PartialView(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var model = service.TaskActions.Find(id);

            if (model.IsNull())
            {
                return new HttpNotFoundResult();
            }

            var viewModel = BuildDeletionViewModel(model);

            if (viewModel.CanDelete
                && PerformAction(() => service.TaskActions.Delete(id, CurrentUser.ID)))
            {
                return Json(new {success = true});
            }

            return PartialView(viewModel);
        }

        private IQueryable<TaskViewModel> GetTaskViewModels(long phaseId)
        {
            var taskCollection =
                service.TaskActions.AllForJob(CurrentJob.ID)
                    .AsQueryable()
                    .Where(p => p.PhaseID.Equals(phaseId));

            return
                taskCollection.Select(
                    x =>
                        new TaskViewModel
                        {
                            ID = x.ID,
                            DefaultCommodity =
                                x.DefaultCommodity == null ? string.Empty : x.DefaultCommodity.CommodityCode,
                            DefaultCommodityID = x.DefaultCommodityID,
                            DisplayOrder = x.DisplayOrder,
                            JobID = x.JobID,
                            Title = x.Title
                        });
        }

        private Task ConvertViewModelToModel(TaskViewModel viewModel)
        {
            return Mapper.Map<Task>(viewModel);
        }

        private TaskViewModel ConvertModelToViewModel(Task model)
        {
            var viewModel = Mapper.Map<TaskViewModel>(model);
            AddCommodityListToViewModel(viewModel);
            return viewModel;
        }

        private void AddCommodityListToViewModel(TaskViewModel viewModel)
        {
            var commodities =
                service.CommodityActions.Search(CurrentJob.ID, "")
                    .Select(x => new SelectListItem {Value = x.ID.ToString(), Text = x.DisplayName});
            var selectListSeed = new List<SelectListItem>(commodities);
            selectListSeed.Insert(0, new SelectListItem {Value = null, Text = string.Empty});

            viewModel.Commodities = new SelectList(selectListSeed, "Value", "Text");
        }

        private DeletionViewModel<TaskViewModel> BuildDeletionViewModel(Task model)
        {
            return new DeletionViewModel<TaskViewModel>(
                ConvertModelToViewModel(model),
                service.TaskActions.ValidateDelete(model.ID));
        }

        private void PropogateCommodity(bool propogateCommodity, long taskId, long? defaultCommodityID)
        {
            if (propogateCommodity)
            {
                service.PropogateCommodityByTask(taskId, defaultCommodityID);
            }
        }
    }
}

MMR.TOPControls.Web/Areas/Admin/Views/Task/Create.cshtml
@using MMR.TOPControls.Web.Helpers;

@model MMR.TOPControls.Web.Areas.Admin.ViewModels.CreateTaskViewModel
@using (Html.BeginForm("Create","Task",new {phaseId = Model.PhaseID}, FormMethod.Post, new { data_form_action = "create" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><i class="icon-remove" /></button>
        <h3>Create New Task</h3>
    </div>
    <div class="modal-body form-horizontal">
        @Html.HiddenFor(x => x.ID)
        @Html.HiddenFor(x => x.JobID)
        @Html.HiddenFor(x => x.PhaseID)
        <div class="control-group">
            @Html.LabelFor(x => x.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.Title)
                @Html.ValidationMessageFor(x => x.Title)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.DisplayOrder, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.DisplayOrder)
                @Html.ValidationMessageFor(x => x.DisplayOrder)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.Commodities, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(x => x.DefaultCommodityID, Model.Commodities, new { @class = "input-block-level", data_select2_default = Model.DefaultCommodityID })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.PropogateCommodity, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.PropogateCommodity)
                @Html.ValidationMessageFor(x => x.PropogateCommodity)
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btnCancel" data-dismiss="modal">Cancel</button>
    </div>    
}

MMR.TOPControls.Web/Areas/Admin/Views/Task/Delete.cshtml
@using MMR.TOPControls.Web.Helpers;
@using MMR.TOPControls.Web.Areas.Admin.ViewModels;
@using MMR.TOPControls.Web.ViewModels;

@model DeletionViewModel<TaskViewModel>
@using (Html.BeginForm(null, null, FormMethod.Post, new { data_form_action = "delete" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><i class="icon-remove" /></button>
        <h3>Confirm Delete Task</h3>
    </div>
    <div class="modal-body form-horizontal">
        @Html.HiddenFor(x => x.ID)
        @Html.HiddenFor(x => x.JobID)
        <div class="control-group">
            @Html.LabelFor(x => x.SourceModel.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.DisplayFor(x => x.SourceModel.Title)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.SourceModel.DisplayOrder, new { @class = "control-label" })
            <div class="controls">
                @Html.DisplayFor(x => x.SourceModel.DisplayOrder)
            </div>
        </div>
    </div>
    <div class="modal-footer">
        @if (Model.CanDelete)
        {
            <button type="submit" class="btn btn-danger">Delete</button>
        }
        else
        {
            <label class="bold red align-center">Delete not available for this value.</label>

            foreach (var rv in Model.Messages)
            {
                <label class="align-center">@rv.ErrorMessage</label>
            }
        }
        <button type="button" class="btn btnCancel" data-dismiss="modal">Cancel</button>
    </div>    
}

MMR.TOPControls.Web/Areas/Admin/Views/Task/Edit.cshtml
@using MMR.TOPControls.Web.Helpers;

@model MMR.TOPControls.Web.Areas.Admin.ViewModels.TaskViewModel
@using (Html.BeginForm(null, null, FormMethod.Post, new { data_form_action = "edit" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><i class="icon-remove" /></button>
        <h3>Edit Task</h3>
    </div>
    <div class="modal-body form-horizontal">
        @Html.HiddenFor(x => x.ID)
        @Html.HiddenFor(x => x.JobID)
        <div class="control-group">
            @Html.LabelFor(x => x.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.Title)
                @Html.ValidationMessageFor(x => x.Title)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.DisplayOrder, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.DisplayOrder)
                @Html.ValidationMessageFor(x => x.DisplayOrder)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.Commodities, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(x => x.DefaultCommodityID, Model.Commodities, new { @class = "input-block-level", data_select2_default = Model.DefaultCommodityID })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(x => x.PropogateCommodity, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(x => x.PropogateCommodity)
                @Html.ValidationMessageFor(x => x.PropogateCommodity)
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btnCancel" data-dismiss="modal">Cancel</button>
    </div>    
}

MMR.TOPControls.Web/Areas/Admin/Views/Task/List.cshtml
@model MMR.TOPControls.Web.Areas.Admin.ViewModels.TaskListViewModel

@{
    ViewBag.Title = String.Format("{0} - Tasks", Model.Phase.Title);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
	<h2>
		@ViewBag.Title
		<span class="pull-right">
            @Html.ActionLink("Create New", "Create", new { phaseId = Model.Phase.ID }, new { @class = "btn btn-primary", data_button_action = "create" })
        </span>
        <span class="clearfix"></span>
	</h2>
</div>

<div id="table-container">
	@{Html.RenderPartial("_ListItems",Model.PhaseTasks);}
</div>

<div id="modal-container" class="modal hide">
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            TopControls.task.editLink = '@Html.ActionLink(" ", "Edit", new { id = "idPlaceholder" }, new { @class = "icon-edit inline-block", title = "Edit", data_button_action="edit" })';
            TopControls.task.deleteLink = '@Html.ActionLink(" ", "Delete", new { id = "idPlaceholder" }, new { @class = "icon-remove inline-block", title = "Delete", data_button_action="delete" })';
			TopControls.task.listUrl = '@Url.Action("ListItems", new { phaseId= Model.Phase.ID})';
            TopControls.task.init();
        });
    </script>
}

MMR.TOPControls.Web/Areas/Admin/Views/Task/_ListItems.cshtml
@using MMR.TOPControls.Web.Helpers;
@model IEnumerable<MMR.TOPControls.Web.Areas.Admin.ViewModels.TaskViewModel>
<table id="task-table" class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayName(x => x.First().Title)</th>
            <th>@Html.DisplayName(x => x.First().DisplayOrder)</th>
            <th>@Html.DisplayName(x => x.First().DefaultCommodityID)</th>
            <th>@Html.DisplayName(x => x.First().DefaultCommodity)</th>
            <th></th> <!--    ID     -->
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>